# Generated by Django 2.1.5 on 2020-11-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stories_story_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='story_summary',
            new_name='story_intro',
        ),
    ]
