# Generated by Django 2.1.5 on 2020-11-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Data_a',
        ),
    ]
