# Generated by Django 2.1.5 on 2020-11-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201118_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_a',
            new_name='Dataa',
        ),
    ]
